version: "3" # composeファイルのバージョン
services: 
    go: # サービス名
        build: . # ①ビルドに使うDockerfileの場所
        tty: true # ②コンテナの永続化
        ports: # ホストOSのポートとコンテナのポートをつなげる 
            - "8080:8080"
        volumes:
            - .:/go/src/my_apps/post_app # ③マウントディレクトリ
